### ISSUE TITLE
issue with Loki 

### ISSUE THREAD

**Issue by Alfraidi0** [eduardomcm/VelociraptorCompetition#1]
I have been trying to use Loki plugin without any luck.
vql: split_recoreds: open C:\Users\ABC\AppData\Local\Temp\temp\temp2234233\loki\mymachine-loki-log-file.csv: The system cannon find the file specific , unable to fallback to ntfs parsing: Not found

**Comment by eduardomcm** [comment]
Hi @Alfraidi0 [Alfraidi0](https://github.com/Alfraidi0), this artifact needs some preparation before you can run it.

The steps are described within the description of the artifact, but basically you need to download the loki zip AND signature-base separately, unzip the "signature-base-master" and Loki folders, rename "signature-base-master" to "signature-base" and place the folder within the /loki folder. Then zip the /loki folder again and upload that to your Loki tool in Velociraptor.

These steps are needed because Loki has its signature base developed separately from the main project (so they can be updated constantly), so you need to put them together prior to using this artifact.
